version: "3.8"

services:
  msr-lean:
    image: roti01acr.azurecr.io/msr-1015-lean-original-recipe:Fixes_24-01-16 
    ports:
     - ${HOST_PORT_PREFIX}55:5555
    volumes:
      - ${HOST_MSR_LICENSE_FILE}:/tmp/license.xml
      - ./application.properties:/tmp/application.properties
    environment:
      - SAG_IS_LICENSE_FILE=/tmp/license.xml
      - SAG_IS_CONFIG_PROPERTIES=/tmp/application.properties
